name: flutter_x_database

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  sqflite:
  path: 



  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true

 